# Generated by Django 4.2.23 on 2025-08-29 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('score', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('score', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('score', models.IntegerField(default=1)),
                ('description', models.TextField(default='', max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstName', models.CharField(default='user_first_name', max_length=250)),
                ('lastName', models.CharField(default='user_last_name', max_length=250)),
                ('userName', models.CharField(max_length=250)),
                ('age', models.IntegerField(default=18)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('activity_score', models.IntegerField(default=0)),
                ('frequency_score', models.IntegerField(default=0)),
                ('status_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('score', models.IntegerField(default=1)),
                ('description', models.TextField(default='', max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('score', models.IntegerField(default=1)),
                ('description', models.TextField(default='', max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routino_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_activity', to='routino_app.activity')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_profile', to='routino_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routino_app.activity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routino_app.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routino_app.profile')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routino_app.routine')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routino_app.status')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routino_app.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routino_app.category'),
        ),
        migrations.AddField(
            model_name='activity',
            name='frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routino_app.frequency'),
        ),
        migrations.AddField(
            model_name='activity',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routino_app.profile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routino_app.status'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routino_app.subcategory'),
        ),
    ]
