# Generated by Django 4.2.13 on 2025-08-31 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routino_app', '0004_auto_20250830_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='goal',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routino_app.activity'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routino_app.category'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routino_app.profile'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='routine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routino_app.routine'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routino_app.status'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='subCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routino_app.subcategory'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routine_activity', to='routino_app.activity', verbose_name='Routine Activity'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routine_profile', to='routino_app.profile', verbose_name='Routine Profile'),
        ),
    ]
