# Generated by Django 4.2.13 on 2025-08-31 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routino_app', '0005_remove_profile_email_alter_goal_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
