# Generated by Django 4.2.13 on 2025-08-31 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routino_app', '0006_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='activity',
        ),
        migrations.AlterField(
            model_name='routine',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_profile', to='routino_app.profile', verbose_name='Routine Profile'),
        ),
        migrations.AddField(
            model_name='routine',
            name='activity',
            field=models.ManyToManyField(related_name='routine_activities', to='routino_app.activity', verbose_name='Routine Activities'),
        ),
    ]
