# Generated by Django 5.2.7 on 2025-11-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routino_app', '0007_remove_routine_activity_alter_routine_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='activity',
            new_name='activities',
        ),
    ]
